import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import Navbar from "@/app/components/navbar";

const montserrat = Montserrat({ subsets: ["latin"], weight: "500" })

export const metadata: Metadata = {
  title: "Music",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={montserrat.className}>
      <link rel="icon" href="https://e-cdn-files.dzcdn.net/cache/images/common/favicon/favicon.5e8e3be4042b873a7358.ico" sizes="any" />
      <body>
        <div>
          <Navbar />
        </div>
        {children}
      </body>
    </html>
  );
}
